project:
  type: website
  output-dir: docs
  
website:
  title: "Vilgot's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
      - posts.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/vilgothuhn
      - icon: github
        href: https://github.com/vilgot-huhn/mywebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Vilgot Huhn"

format:
  html:
    theme: lux
    toc: true

editor: source

